#!/usr/bin/env python3
"""Render an actual --nocapture reference test log as a conformance snapshot.
Usage: cargo test --test reference -- --nocapture > target/reference.log 2>&1
       python tests/reference/report.py target/reference.log > tests/reference/results.md
Never infer counts from manifest size or exempt fixtures as passes.
"""
import pathlib
import re
import sys

log = pathlib.Path(sys.argv[1]).read_text()
summaries = {}
for prefix in ('REFERENCE', 'COMPAT'):
    pattern = rf'{prefix}_COUNTS gated=(\d+) divergent=(\d+) host_converted=(\d+) pending=(\d+) failures=(\d+)'
    values = re.findall(pattern, log)
    if len(values) != 1:
        raise SystemExit(f'Expected one {prefix} summary, got {len(values)}')
    summaries[prefix] = values[0]

print('# Reference results\n\nGenerated by `tests/reference/report.py` from actual test output.\n')
print('| Suite | Gated pass | Divergent measured | Host converted | Pending | Failures |')
print('|---|---:|---:|---:|---:|---:|')
for prefix, title in [('REFERENCE', 'Historical FFmpeg'), ('COMPAT', 'Direct libass 0.17.5')]:
    print('| ' + title + ' | ' + ' | '.join(summaries[prefix]) + ' |')
print('\n| Fixture | IoU | Ink ratio | Mean error | Hard fraction | Status |\n|---|---:|---:|---:|---:|---|')
for line in log.splitlines():
    old = re.match(r'(\S+)\s+ours_ink=\s*(\d+) ref_ink=\s*(\d+) iou=([\d.]+) mean_err=\s*([\d.]+) hard_frac=([\d.]+)(.*)', line)
    new = re.match(r'COMPAT (\S+) iou=([\d.]+) ratio=([\d.]+) mean=([\d.]+) hard=([\d.]+)', line)
    if old:
        name, ours, ref, iou, mean, hard, reason = old.groups()
        status = ('Divergent measured' if 'known-divergent' in reason else
                  'Measured; suite failed' if int(summaries['REFERENCE'][-1]) else 'Gated')
        print(f'| {name} | {iou} | {int(ours)/max(int(ref),1):.3f} | {mean} | {hard} | {status} |')
    elif new:
        name, iou, ratio, mean, hard = new.groups()
        status = 'Measured; suite failed' if int(summaries['COMPAT'][-1]) else 'Gated'
        print(f'| {name} | {iou} | {ratio} | {mean} | {hard} | {status} |')
