use crate::types::ScriptInfo;

use super::errors::ParseError;

pub fn parse_script_info(lines: &[&str], start_line: usize) -> Result<ScriptInfo, ParseError> {
    let mut info = ScriptInfo::new();

    for (i, line) in lines.iter().enumerate() {
        let line = line.trim();

        // Skip empty lines and comments
        if line.is_empty() || line.starts_with(';') {
            continue;
        }

        // Parse key:value pairs
        if let Some((key, value)) = parse_key_value(line) {
            info.set_field(&key, &value)
                .map_err(|e| ParseError::line_error(start_line + i, e))?;
        } else {
            return Err(ParseError::line_error(
                start_line + i,
                format!("Invalid line in Script Info: {}", line),
            ));
        }
    }

    Ok(info)
}

fn parse_key_value(line: &str) -> Option<(String, String)> {
    let colon_pos = line.find(':')?;
    let key = line[..colon_pos].trim().to_string();
    let value = line[colon_pos + 1..].trim().to_string();

    if key.is_empty() {
        return None;
    }

    Some((key, value))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::YCbCrMatrix;

    #[test]
    fn test_parse_script_info_basic() {
        let lines = vec![
            "; Script generated by Example",
            "Title: Test Subtitle",
            "ScriptType: v4.00+",
            "PlayResX: 1920",
            "PlayResY: 1080",
        ];

        let info = parse_script_info(&lines, 0).unwrap();
        assert_eq!(info.title.as_deref(), Some("Test Subtitle"));
        assert_eq!(info.play_res_x, 1920);
        assert_eq!(info.play_res_y, 1080);
    }

    #[test]
    fn test_parse_script_info_with_boolean() {
        let lines = vec!["ScaledBorderAndShadow: yes", "WrapStyle: 0"];

        let info = parse_script_info(&lines, 0).unwrap();
        assert!(info.scaled_border_and_shadow);
        assert_eq!(info.wrap_style, 0);
    }

    #[test]
    fn test_parse_script_info_empty() {
        let lines: Vec<&str> = vec![];
        let info = parse_script_info(&lines, 0).unwrap();
        assert_eq!(info.play_res_x, 1920); // default
    }

    #[test]
    fn test_parse_script_info_invalid_line() {
        let lines = vec!["This is not valid"];
        let result = parse_script_info(&lines, 0);
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_all_libass_ycbcr_matrix_values() {
        for (value, expected) in [
            ("Default", YCbCrMatrix::Default),
            ("Unknown", YCbCrMatrix::Unknown),
            ("None", YCbCrMatrix::None),
            ("TV.601", YCbCrMatrix::TV601),
            ("PC.601", YCbCrMatrix::PC601),
            ("TV.709", YCbCrMatrix::TV709),
            ("PC.709", YCbCrMatrix::PC709),
            ("TV.240m", YCbCrMatrix::TV240M),
            ("PC.240m", YCbCrMatrix::PC240M),
            ("TV.FCC", YCbCrMatrix::TVFCC),
            ("PC.FCC", YCbCrMatrix::PCFCC),
        ] {
            let line = format!("YCbCr Matrix: {value}");
            let info = parse_script_info(&[line.as_str()], 1).unwrap();
            assert_eq!(info.y_cb_cr_matrix, expected, "{value}");
        }
    }
}
